{
 "title": "Cilium / High Level Health",
 "description": "High level overview dashboard for Cilium (https://cilium.io/). At a glance, should provide strong indicators of potential issues in the cluster.  Indicators here are designed to providen opinionated thresholds on problematic Cilium metrics.",
 "tags": [ "cilium-overview" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "3" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "💓 Cilium Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cilium Health",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Cilium Health\n\n#### ℹ️ Provides high level health indicators on Cilium components, including Kubernetes level checks such as whether components are in a running state (i.e. not Pending/Crashing etc).\n\n"
   }
  },
  {
   "title": "Agent Pods Not Running",
   "type": "stat",
   "description": "Tracks the number of Cilium Agents that are not in the Running state.  This could indicate Pods that are crashing, cannot be scheduled (i.e. Pending), image pull issues etc.\n\nCilium Agents that are not running will disrupt Pod scheduling, may affect policy implementation and can lead to disruption in L7 proxy functionality.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cilium Agents" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{pod=~\"cilium-[0-9a-z]+\", phase!=\"Running\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} == 1 or kube_pod_container_status_waiting_reason{pod=~\"cilium-[0-9a-z]+\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Pod Restarts Since",
   "type": "stat",
   "description": "This is the total number of times Cilium components have restarted in the given time range.\n\nSee the following documentation for more information about different Cilium Enterprise components: \n\nhttps://docs.isovalent.com/operations-guide/architecture/index.html#cilium-components ",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"cilium-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Cilium Agent Restarts"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"cilium-operator-.*\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "Cilium Operator Restarts"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"cilium-dnsproxy-.*\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Cilium DNSProxy Restarts"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"cilium-envoy-.*\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Cilium Envoy DaemonSet Restarts"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"cilium*\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Other Cilium Workload Restarts"
    }
   ]
  },
  {
   "title": "Cilium Operator Error and Warning Rate",
   "type": "stat",
   "description": "Rate of errors and warnings emitted by Cilium Operator or Agents.\n\nErrors: Generally indicate significant problems in runtime operations of Cilium components.  Any increase should be investigated as it may indicate other issues.\n\nWarnings: Warnings may indicate unexpected runtime operations of Cilium or unexpected configuration states.   An unexpected sudden increase of warnings may indicate underlying issues and should be investigated. ",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", pod=~\"$pod\", instance=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod, level))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Reconciliation Errors Since",
   "type": "stat",
   "description": "While running, Cilium performs various reconciliation tasks to achieve the desired configuration state.\n\nReconciliation tasks failing may indicate various issues with Ciliums ability to implemented the desired config state.\nErrors here could indicate potential degradation of functionality and should be investigated. \n\nDocumentation on how to check controller state: https://docs.cilium.io/en/stable/cmdref/cilium_status/",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reconcile errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cilium_controllers_runs_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", status=\"failure\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Reconciliation Error Rate",
   "type": "timeseries",
   "description": "For the runtime functionality of Cilium, Cilium agents run reconciliation tasks (known as \"controllers\").\n\nThese attempt to reconcile Cilium configuration with implemented runtime state (ex. implementing network policy configuration).\n\nThese tasks are crucial to the functionality of Cilium, errors here may indicate issues with configuration being out of sync with realized state.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reconcile errors" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", status=\"failure\"}[$__rate_interval])) by (pod, status)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "🌐 Cilium Network Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Failing Cilium Node Health Checks",
   "type": "status-history",
   "description": "If enabled (default=true), Cilium Agents attempt to performs connectivity health checks against all other nodes in the cluster.\n\nFailures here could indicate connectivity issues between Pod workloads between those nodes.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk($k, count(cilium_node_connectivity_status{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} != 1) by (pod))\n",
     "legendFormat": "Connectivity Status: {{pod}}"
    }
   ]
  },
  { "title": "📋 Cilium CNI (Pod Scheduling)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CNI",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "### Pod Scheduling\n\nThese metrics cover the Cilium-specific component of Pod Scheduling: CNI operations.\n\nThese values use the mean of the most recent requests. They will not change if there have been no recent requests.\n\nℹ️ **Errors or high latency could indicate issues with Pod scheduling and should be investigated.**\n\n"
   }
  },
  {
   "title": "CNI Error Rate",
   "type": "stat",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_api_limiter_processed_requests_total{pod=~\"$pod\", api_call=~\"endpoint.*\", outcome=\"fail\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max CNI Add Latency",
   "type": "stat",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 4, "w": 10, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-create\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max CNI Delete Latency",
   "type": "stat",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Max(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-delete\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CNI Error Rate",
   "type": "timeseries",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_api_limiter_processed_requests_total{pod=~\"$pod\", api_call=~\"endpoint.*\", outcome=\"fail\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "err/s"
    }
   ]
  },
  {
   "title": "CNI Add Latency",
   "type": "timeseries",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-create\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-create\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-create\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CNI Delete Latency",
   "type": "timeseries",
   "description": "CNI (Container Network Interface [1]) is a API specification for the creation and configuration of container (in the case of Kubernetes Pod containers) networking.\n\nCilium implements CNI for Kubernetes Pod scheduling.  The functioning of Ciliums CNI is a key component in the functionality of Cilium.  Errors here will likely indicate Pod scheduling issues.\n\n[1] https://github.com/containernetworking/cni",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-delete\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-delete\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "min(cilium_api_limiter_processing_duration_seconds{pod=~\"$pod\", api_call=~\"endpoint-delete\", value=\"mean\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CNI",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "# Pod IP States\n\nCilium moves Pod IPs (Cilium Endpoints) through a series of states during initialization and cleanup.\n\nHere, in the steady-state, you should expect to see 100% in the ready state. \n\nℹ️ **If you see a number of Endpoints \"stuck\" in a non-ready state, it may indicate problems with resource saturation that should be investigated.**\n\nCilium Endpoint Lifecycle: https://docs.cilium.io/en/stable/security/policy/lifecycle/#id2"
   }
  },
  {
   "title": "% of Pods in State",
   "type": "timeseries",
   "description": "todo",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "(sum by(endpoint_state) (cilium_endpoint_state{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) / ignoring(endpoint_state) group_left sum(cilium_endpoint_state{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "🏭 Kubernetes Event Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Kubernetes Events Processing",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "# Kubernetes **Events Processing**\n\nCilium consumes Kubernetes events about resources such as Network Policies, Pod networking, Nodes, and others to implement networking behavior.\n\nIn order for Cilium to function properly it must be able to communicate with Kubernetes APIServer and react to these events.\n\nThis section provides an indication of the health of Kubernetes event ingestion.\n\nℹ️ **Errors or high latency here could indicate resource constraints (CPU, Memory) on the Cilium Agent or the Kubernetes Control Plane**"
   }
  },
  {
   "title": "Kubernetes Event Rate",
   "type": "timeseries",
   "description": "Cilium consumes Kubernetes events for updates regarding various CRD resources.  Notably:\n\n* Network Policy Types: CiliumNetworkPolicies, CiliumClusterwideNetworkPolicies, NetworkPolicies.\n* Pods\n* Nodes\n* etc\n\nThe consuming and processing of these events is critical for Cilium Agents to be in sync with changes in Kubernetes cluster state or configuration (i.e. such as new Pods, policy changes etc).\n\nThus Kubernetes events are crucial to various aspects of Cilium including:\n\n* Connectivity\n* Network Policy\n* Pod Scheduling\n* Proxy Configuration\n\nUnexpected spikes or drops in event rate may indicate issues.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes Client API Latency",
   "type": "timeseries",
   "description": "Cilium consumes Kubernetes events for updates regarding various CRD resources.  Notably:\n\n* Network Policy Types: CiliumNetworkPolicies, CiliumClusterwideNetworkPolicies, NetworkPolicies.\n* Pods\n* Nodes\n* etc\n\nThe consuming and processing of these events is critical for Cilium Agents to be in sync with changes in Kubernetes cluster state or configuration (i.e. such as new Pods, policy changes etc).\n\nThus Kubernetes events are crucial to various aspects of Cilium including:\n\n* Connectivity\n* Network Policy\n* Pod Scheduling\n* Proxy Configuration\n\nUnexpected spikes or drops in event rate may indicate issues.",
   "gridPos": { "h": 11, "w": 9, "x": 5, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cilium_k8s_client_api_latency_time_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cilium_k8s_client_api_latency_time_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cilium_k8s_client_api_latency_time_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Kubernetes Client API Rate Limiter Latency",
   "type": "timeseries",
   "description": "Cilium consumes Kubernetes events for updates regarding various CRD resources.  Notably:\n\n* Network Policy Types: CiliumNetworkPolicies, CiliumClusterwideNetworkPolicies, NetworkPolicies.\n* Pods\n* Nodes\n* etc\n\nThe consuming and processing of these events is critical for Cilium Agents to be in sync with changes in Kubernetes cluster state or configuration (i.e. such as new Pods, policy changes etc).\n\nThus Kubernetes events are crucial to various aspects of Cilium including:\n\n* Connectivity\n* Network Policy\n* Pod Scheduling\n* Proxy Configuration\n\nUnexpected spikes or drops in event rate may indicate issues.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cilium_k8s_client_rate_limiter_duration_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cilium_k8s_client_rate_limiter_duration_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cilium_k8s_client_rate_limiter_duration_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "🗄️ BPF Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "BPF Map Health",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "options": {
      "content": "# BPF Map Health\n\nCilium uses BPF maps as a datastore.\n\nℹ️ **These maps are fundamental to Cilium's operation. If they reach capacity then related functionality may fail.**\n\nBPF Maps and Map Capacity: https://docs.cilium.io/en/stable/network/ebpf/maps/#bpf-map-limitations."
     }
    },
    {
     "title": "Error Rate by Map",
     "type": "timeseries",
     "description": "This is a low level indicator that provides a rate of errors for insertions in local Endpoint Policy BPF Maps.\n\nEndpoint policy BPF maps act as a datastore for individual Cilium Endpoints running on the Cilium Agents node.\n\nThe Endpoint Policy BPF Maps are critical to the functioning of Cilium Endpoint connectivity. Errors here are considered unexpected and should be investigated.\n\nOne potential cause is high FQDN IP cache utilization. To check this, take a look at the L7 Dashboard for FQDN IP allocations as well as under the Agent Policy engine for Identities and Identity allocation rates.\nAn increase of error rates here, coupled with increases to those indicator strongly imply issues with FQDN proxies.",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "errs/sec" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_bpf_map_ops_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", outcome=\"fail\"}[$__rate_interval])) by (map_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Map Utilization",
     "type": "timeseries",
     "description": "Provides current \"pressure\" on BPF maps which act as data stores for Cilium agents.  High pressure can indicate overutilization of BPF maps and may lead to degradation of functionality.",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(cilium_bpf_map_pressure{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (map_name)",
       "legendFormat": "Map: {{map_name}}"
      }
     ]
    },
    {
     "title": "Map Utilization",
     "type": "stat",
     "description": "Provides current \"pressure\" on BPF maps which act as data stores for Cilium agents.  High pressure can indicate overutilization of BPF maps and may lead to degradation of functionality.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cilium_bpf_map_pressure{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (map_name)",
       "legendFormat": "Map: {{map_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔁 Reconciliation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation Status",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "options": {
      "content": "# Reconciliation Loops\n\nCilium implements reconciliation operations and other periodic operations using the concept of controllers.\n\nEach of these controllers is grouped under a name which relates to a subsystem, resource type, or operation.\n\nℹ️ **Error rates that appear here can help you to narrow down issues related to a failing Cilium component.**"
     }
    },
    {
     "title": "Controller Run Outcome Rate",
     "type": "stat",
     "description": "For the runtime functionality of Cilium, Cilium agents run reconciliation tasks (known as \"controllers\").\n\nThese attempt to reconcile Cilium configuration with implemented runtime state (ex. implementing network policy configuration).\n\nThese tasks are crucial to the functionality of Cilium, errors here may indicate issues with configuration being out of sync with realized state.",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cilium_controllers_runs_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Per Controller Error Rate",
     "type": "stat",
     "description": "For the runtime functionality of Cilium, Cilium agents run reconciliation tasks (known as \"controllers\").\n\nThese attempt to reconcile Cilium configuration with implemented runtime state (ex. implementing network policy configuration).\n\nThese tasks are crucial to the functionality of Cilium, errors here may indicate issues with configuration being out of sync with realized state.",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "err/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cilium_controllers_group_runs_total{status=\"failure\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (group_name)",
       "legendFormat": "{{group_name}}"
      }
     ]
    },
    {
     "title": "Controller Run Outcome Rate",
     "type": "timeseries",
     "description": "For the runtime functionality of Cilium, Cilium agents run reconciliation tasks (known as \"controllers\").\n\nThese attempt to reconcile Cilium configuration with implemented runtime state (ex. implementing network policy configuration).\n\nThese tasks are crucial to the functionality of Cilium, errors here may indicate issues with configuration being out of sync with realized state.",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_controllers_runs_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Reconciliation Tasks  ",
     "type": "timeseries",
     "description": "For the runtime functionality of Cilium, Cilium agents run reconciliation tasks (known as \"controllers\").\n\nThese attempt to reconcile Cilium configuration with implemented runtime state (ex. implementing network policy configuration).\n\nThese tasks are crucial to the functionality of Cilium, errors here may indicate issues with configuration being out of sync with realized state.",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "err/s" } },
     "targets": [
      {
       "expr": "topk($k, sum(increase(cilium_controllers_group_runs_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod, group_name))",
       "legendFormat": "{{group_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "⚖️ Policy Enforcement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    { "title": "L7 Proxy", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 }, "options": { "content": "# Policy Engine" } },
    {
     "title": "Policy Implementation Latency",
     "type": "stat",
     "description": "Policy implementation delay tracks how much time is spent waiting for policy configuration to be implemented into current Cilium network policy. Poor performance may indicate problems with Ciliums policy engine.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
    },
    {
     "title": "Policy Implementation Latency",
     "type": "timeseries",
     "description": "Policy implementation delay tracks how much time is spent waiting for policy configuration to be implemented into current Cilium network policy. Poor performance may indicate problems with Ciliums policy engine.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } }
    },
    {
     "title": "L7 Proxy",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "options": {
      "content": "# Policy: **L7 Proxy**\n\nThis section covers processing of requests done on behalf of L7 proxies in Cilium:\n\n* Cilium Agent DNS Proxy (default)\n* External HA DNS Proxy (requires additional configuration)\n* Cilium L7 Envoy Proxy"
     }
    },
    {
     "title": "L7 Proxy Request Errors",
     "type": "stat",
     "description": "This tracks errors that Cilium L7 proxies (i.e. DNSProxy and Envoy L7) encounter while processing request responses.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "errors/sec" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cilium_policy_l7_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", rule=\"parse_errors\"}[$__rate_interval])) by (proxy_type)",
       "legendFormat": "{{proxy_type}}"
      }
     ]
    },
    {
     "title": "L7 Request Processing Rate",
     "type": "stat",
     "description": "Rates for processing L7 requests.\n\nIncreases or persistent rates of errors here likely indicate problems with Cilium, but may also indicate issues with application requests or upstream services such as DNS.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cilium_policy_l7_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (proxy_type)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "DNS Proxy Upstream Reply Seconds Duration",
     "type": "stat",
     "description": "Provides time waiting for proxies DNS requests via Ciliums DNS Proxy to complete. Issues here may indicate problems with upstream DNS servers or configuration.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cilium_proxy_upstream_reply_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Alloc/Sec"
      }
     ]
    },
    {
     "title": "L7 Proxy Request Errors",
     "type": "timeseries",
     "description": "This tracks errors that Cilium L7 proxies (i.e. DNSProxy and Envoy L7) encounter while processing request responses.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "errors/sec" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_policy_l7_total{pod=~\"$pod\", rule=\"parse_errors\", pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (proxy_type)",
       "legendFormat": "Errors: {{proxy_type}}"
      }
     ]
    },
    {
     "title": "L7 Request Processing Rate",
     "type": "timeseries",
     "description": "Rates for processing L7 requests.\n\nIncreases or persistent rates of errors here likely indicate problems with Cilium, but may also indicate issues with application requests or upstream services such as DNS.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
     "targets": [
      {
       "expr": "sum(rate(cilium_policy_l7_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (proxy_type)",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "DNS Proxy Upstream Reply Seconds Duration",
     "type": "timeseries",
     "description": "Rates for processing L7 requests.\n\nIncreases or persistent rates of errors here likely indicate problems with Cilium, but may also indicate issues with application requests or upstream services such as DNS.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cilium_proxy_upstream_reply_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "P95 Latency"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(cilium_proxy_upstream_reply_seconds_bucket{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50 Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "💻 Cilium System CPU/Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "Cilium Agent CPU Runtime Latency",
   "type": "stat",
   "description": "This metric provides the 90th and 50th (i.e. median) percentile of Cilium agent run-time scheduling.\n\nThis is related to CPU availability and utilization, high values or increases here denote in either throttling or lack of compute resources.\n\nHigh sustained runtime will likely indicate problems with Cilium functionality.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"cilium-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(go_sched_latencies_seconds_bucket{pod=~\"cilium-[a-z0-9]+\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Cilium Agent Container Memory Utilization",
   "type": "stat",
   "description": "Total memory utilization of Cilium Agent Pods",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, sum(container_memory_rss{pod=~\"$pod\", pod=~\"cilium.*\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Agent Container CPU Utilization",
   "type": "stat",
   "description": "Provides top-k Cilium Agent CPU utilization metrics.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "seconds/second" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cilium Agent Container Memory Utilization",
   "type": "timeseries",
   "description": "Total memory utilization of Cilium Agent Pods",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, sum(container_memory_rss{pod=~\"$pod\", pod=~\"cilium.*\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Agent Container CPU Utilization",
   "type": "timeseries",
   "description": "Provides top-k Cilium Agent CPU utilization metrics.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "seconds/second" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cilium Agent Container Memory Limit Utilization",
   "type": "timeseries",
   "description": "This shows how close Cilium workload Pods are to their set memory limits (if set).  By default Cilium installs without explicit memory limits - in which case nothing should be shown here.\n\nHowever if Cilium has a memory limit set this will show how much of their limit Cilium Pods are using.\n\nPods that hit their limit will be killed for running out of memory by the Linux host OS and can cause disruptions in functionality.\n\nConsistently high values here should indicate that you may want to increase limits.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "(sum by (pod, container)(container_memory_rss{pod=~\"$pod\", pod=~\"cilium-[a-z0-9]\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})) / (sum by (pod, container) (kube_pod_container_resource_limits{pod=~\"$pod\", pod=~\"cilium-[a-z0-9]\", namespace=~\"$namespace\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}