{
 "title": "Tetragon / Network Interface Metrics",
 "tags": [ "Tetragon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(tetragon_interface_txbytes,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(tetragon_interface_txbytes{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(tetragon_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(tetragon_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Egress per Namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ingress per Namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_rxbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interface TX/RX Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Network Interface TX Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_txbytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_rxbytes{cluster=~\"$cluster\", namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Segments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_txsegs{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_rxsegs{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_txdrops{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_rxdrops{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface TX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_txerrors{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Network Interface RX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tetragon_interface_rxerrors{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",name=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ name }} {{ pod }}"
    }
   ]
  }
 ]
}